language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '9'
  - '8'
  - '6'
  - '10'
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
before_install:
  - npm install -g npm@5
  - npm install -g greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
